apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-redis
  namespace: payment-system
  labels:
    app: userservice-redis
    tier: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-redis
  template:
    metadata:
      labels:
        app: userservice-redis
        tier: infra
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5