apiVersion: v1
kind: ConfigMap
metadata:
  name: orderservice-config
  namespace: payment-system
data:
  SERVER_PORT: "8083"
  SPRING_PROFILES_ACTIVE: "docker"
  DB_URL: "jdbc:postgresql://orderservice-db:5432/order_db"
  USER_SERVICE_URL: "http://userservice:8082"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/payment-system/protocol/openid-connect/certs"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_CONSUMER_GROUP_ID: "order-service-group"
  KAFKA_TOPIC_PAYMENT_CREATED: "payment-created"