apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
  namespace: payment-system
data:
  SERVER_PORT: "8082"
  SPRING_PROFILES_ACTIVE: "docker"
  DB_URL: "jdbc:postgresql://userservice-db:5432/user_db"
  REDIS_HOST: "userservice-redis"
  REDIS_PORT: "6379"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/payment-system"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/payment-system/protocol/openid-connect/certs"