apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: payment-system
  labels:
    app: userservice
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
        tier: app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: userservice
          image: ghcr.io/dsavitski/payment-system-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: userservice-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: userservice-db-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-db-credentials
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"