apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: payment-system
  labels:
    app: kafka
    tier: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        tier: infra
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          envFrom:
            - configMapRef:
                name: kafka-config
          volumeMounts:
            - name: data
              mountPath: /tmp/kraft-combined-logs
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kafka-pvc